name: dilly_daily
description: Help & Motivate, your meal planner app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  auto_size_text: ^3.0.0
  shared_preferences: ^2.5.3
  food_icons: ^0.0.6
  flutter_emoji: ^2.5.1
  gradient_slider: ^1.0.3
  flutter_test: # Moved here
    sdk: flutter
  path_provider: ^2.1.5
  http: ^1.6.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/image/slider_thumb_cute_primary.png
    - assets/image/meals/
    - assets/data/
  uses-material-design: true

  fonts:
    - family: SkullIcon
      fonts:
        - asset: assets/fonts/SkullIcon.ttf
