name: dilly_daily
description: Help & Motivate, your meal planner app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  #sdk: ">=2.19.4 <4.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.7

  auto_size_text: ^3.0.0
  english_words: ^4.0.0

  clarity_flutter: ^1.6.0
  shared_preferences: ^2.5.3

  food_icons: ^0.0.6
  flutter_emoji: ^2.5.1
  gradient_slider: ^1.0.3

  path: ^1.8.3
  path_provider: ^2.1.5
  provider: ^6.0.0

  http: ^1.6.0
  uuid: ^4.4.2

  image_picker: ^0.8.7+3
  image_cropper: ^11.0.0
  dotted_border: ^3.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  assets:
    - assets/image/slider_thumb_cute_primary.png
    - assets/image/meals/
    - assets/data/
  uses-material-design: true

  fonts:
    - family: SkullIcon
      fonts:
        - asset: assets/fonts/SkullIcon.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/image/icon.png"
    background_color: "#844c72"
    theme_color: "#844c72"
  windows:
    generate: true
    image_path: "assets/image/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/image/icon.png"
